declick_core_main:
    resource: "@DeclickCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
declick_core_project:
    resource: "@DeclickCoreBundle/Resources/config/routing_project.yml"
    prefix:   /project

declick_core_admin:
    resource: "@DeclickCoreBundle/Resources/config/routing_admin.yml"
    prefix:   /admin
    
declick_core_assets:
    resource: "@DeclickCoreBundle/Resources/config/routing_assets.yml"
    prefix:   /assets
    
declick_core_user:
    resource: "@DeclickCoreBundle/Resources/config/routing_profile.yml"
    prefix:   /

declick_core_exercise:
    resource: "@DeclickCoreBundle/Resources/config/routing_exercise.yml"
    prefix:   /exercise

