fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

tangara_user_register:
    path: /register
    defaults: { _controller: TangaraCoreBundle:Profile:register }   

tangara_user_registration_confirmed:
    path: /registration_confirmed
    defaults: { _controller: TangaraCoreBundle:Profile:registrationConfirmed }   

tangara_user_change_password:
    path: /change-password
    defaults: { _controller: TangaraCoreBundle:Profile:changePassword}       

tangara_user_logout:
    path: /tlogout
    defaults: { _controller: TangaraCoreBundle:Profile:logout }
    
tangara_user_profile_show:
    path:  /profile/{user_id}
    defaults: { _controller: TangaraCoreBundle:Profile:profile, user_id: false }

tangara_core_user_menu:
    path:  /user_menu
    defaults: { _controller: TangaraCoreBundle:Profile:menu }

tangara_user_forgotten_password:
    path: /forgotten-password
    defaults: { _controller: TangaraCoreBundle:Profile:forgotPassword}

tangara_user_password_reset_confirmed:
    path: /reset_confirmed
    defaults: { _controller: TangaraCoreBundle:Profile:resetPasswordConfirmed }   

fos_user_resetting_reset:
    path: /reset-password/{token}
    defaults: { _controller: TangaraCoreBundle:Profile:resetPassword }
    
fos_user_resetting_check_email:
    path: /check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    