#tangara_tangarajs_index:
#    pattern:  /
#    defaults: { _controller: TangaraCoreBundle:Project:index }

tangara_tangarajs_get_tangara_files:            
    path:  /getprograms
    defaults: { _controller: TangaraCoreBundle:Assets:getPrograms }

tangara_tangarajs_get_resources:            
    path:  /getresources
    defaults: { _controller: TangaraCoreBundle:Assets:getResources }

tangara_tangarajs_get_program_code:
    path:  /getcode
    defaults: { _controller: TangaraCoreBundle:Assets:getProgramCode }

tangara_tangarajs_get_program_statements:
    path:  /getstatements
    defaults: { _controller: TangaraCoreBundle:Assets:getProgramStatements }

tangara_tangarajs_set_program_content:
    path:  /setprogramcontent
    defaults: { _controller: TangaraCoreBundle:Assets:setProgramContent }

tangara_tangarajs_remove_program:
    path:  /removeprogram
    defaults: { _controller: TangaraCoreBundle:Assets:removeProgram }

tangara_tangarajs_remove_resource:
    path:  /removeresource
    defaults: { _controller: TangaraCoreBundle:Assets:removeResource }
   
tangara_tangarajs_get_resource_1:
    path:  /getresource/{projectId}/{version}/{name}
    defaults: { _controller: TangaraCoreBundle:Assets:getResource }

tangara_tangarajs_get_resource_2:
    path:  /getresource/{version}/{name}
    defaults: { _controller: TangaraCoreBundle:Assets:getResource, projectId: false }


tangara_tangarajs_create_program:
    path:  /createprogram
    defaults: { _controller: TangaraCoreBundle:Assets:createProgram }

tangara_tangarajs_add_resource:
    path:  /addresource
    defaults: { _controller: TangaraCoreBundle:Assets:addResource }

tangara_tangarajs_rename_program:
    path:  /renameprogram
    defaults: { _controller: TangaraCoreBundle:Assets:renameProgram }

tangara_tangarajs_rename_resource:
    path:  /renameresource
    defaults: { _controller: TangaraCoreBundle:Assets:renameResource }

tangara_tangarajs_set_resource:
    path:  /setresource
    defaults: { _controller: TangaraCoreBundle:Assets:setResourceContent }

tangara_tangarajs_duplicate_resource:
    path:  /duplicateresource
    defaults: { _controller: TangaraCoreBundle:Assets:duplicateResource }

tangara_tangarajs_create_resource:
    path:  /createresource
    defaults: { _controller: TangaraCoreBundle:Assets:createResource }
